version: "3"
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/take_home_db
      STRIPE_PUBLISHABLE_KEY: pk_test_51MxozXSB5PoCW6XHnoW8hvGgiA3OFQvs7rL4U8Qnq8LSaALYGnafTkKgBHStHQ9oOsJxwkZJGWWcs7Y3Fl1pN9f600HTf9dlKN
      STRIPE_SECRET_KEY: sk_test_51MxozXSB5PoCW6XHIZg5Dk4mAjfccB47tx8bsJNlJfWwQxBDXfy5sE3cpbkLntera7SFxvP10dgv6CfF3diPIDz500gPKjEiKw  
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: take_home_db
